# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-02 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='eid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
